import type { OfflineProgress } from "../game/save";
import type { DecorationSize } from "../game/tank-catalog";
import type { CoinType, FishGender, FishState, FoodTypeId, Price, StoreTab, Wallet } from "../types/mechanics";

export type AquariumTestSnapshot = {
  coins: number;
  wallet: Wallet;
  foodInventory: number;
  foodInventoryByType: Record<string, number>;
  fishInventoryByType: Record<string, number>;
  fishDeliveryBubbleCount: number;
  timeCurrentRemainingSeconds: number;
  tankActivitySpeedMultiplier: number;
  foodBuyQuantities: Record<string, number>;
  creatureInventoryByType: Record<string, number>;
  activeScreen: string;
  activeTab: StoreTab;
  storeCoinFilter: CoinType;
  fishCatalogLevel: number;
  placementMode: string;
  fishCount: number;
  activeFishCount: number;
  maxFishCapacity: number;
  helperCreatureCount: number;
  activeHelperCreatureCount: number;
  maxHelperCreatures: number;
  tankLevel: number;
  activeTankSlot: number;
  ownedTankLevels: number[];
  ownedTankCount: number;
  maxOwnedTanks: number;
  tankDisplayLevel: number;
  maxTankLevel: number;
  renderScale: number;
  tankCanUpgradeIndefinitely: boolean;
  tankSlotsAreIsolated: boolean;
  fishCatalogMaxLevel: number;
  tankViewScale: number;
  tankWorldBounds: { left: number; top: number; right: number; bottom: number; width: number; height: number };
  tankScreenEdges: { left: number; top: number; right: number; bottom: number };
  totalWealth: number;
  tankWorth: number;
  tankNeedIndicator: string;
  tankHudText: string;
  tankStatusText: string;
  tankCareText: string;
  fishTypeCount: number;
  helperCreatureTypeCount: number;
  visibleFishCatalogCount: number;
  visibleFishCatalogPreviewTextures: string[];
  visibleFishCatalogPreviewStates: Array<{
    id: string;
    requiredLevel: number;
    textureKey: string;
    revealed: boolean;
  }>;
  visibleStoreCatalogCount: number;
  assetCoverage: {
    fish: number;
    food: number;
    decorations: number;
    coins: number;
    uiIcons: number;
    helpers: number;
    backgrounds: number;
  };
  dirtyTankOverlay: {
    visible: boolean;
    alpha: number;
    displayWidth: number;
    displayHeight: number;
  };
  nextTankUpgradePrice?: Price;
  numberFormatSamples: {
    small: string;
    thousand: string;
    million: string;
    billion: string;
  };
  foodCount: number;
  coinDropCount: number;
  decorationCount: number;
  decorations: Array<{ typeId: string; size: DecorationSize; x: number; y: number; depth: number }>;
  decorationTrashTarget: { visible: boolean; x: number; y: number };
  cleanliness: number;
  happiness: number;
  compatibilityScore: number;
  modalTitle?: string;
  saved: boolean;
  offlineProgress: OfflineProgress;
  fish: Array<{
    typeId: string;
    typeName: string;
    textureKey: string;
    state: FishState;
    ageLabel: string;
    ageSeconds: number;
    ageMonths: number;
    ageYears: number;
    growthCapAgeYears: number;
    lengthCm: number;
    weightGrams: number;
    lengthLabel: string;
    weightLabel: string;
    naturalAgeScale: number;
    tankGrowthScaleCap: number;
    growthBlockedByTank: boolean;
    gender: FishGender;
    fatalCareSeconds: number;
    fatalCareRemainingSeconds: number;
    continuousHungrySeconds: number;
    hunger: number;
    health: number;
    x: number;
    y: number;
    scale: number;
    rotation: number;
    displayWidth: number;
    displayHeight: number;
    veryBigScaleCap: number;
    movementSizeMultiplier: number;
    calorieNeedMultiplier: number;
    hungerPerSecond: number;
    mealCaloriesNeeded: number;
    productionSummary: string;
    productionOptions: Array<{
      coinType: CoinType;
      amount: number;
      intervalSeconds: number;
      chance: number;
    }>;
    bodyTint: number;
    sellValue: number;
    nextCoinDropInMs: number;
    emote: {
      x: number;
      y: number;
      emoji: string;
      emojiVisible: boolean;
      emojiX: number;
      emojiY: number;
      emojiBubbleVisible: boolean;
    };
    tailAnimation: {
      wag: number;
      fan: number;
      alpha: number;
      visible: boolean;
    };
  }>;
  foods: Array<{ x: number; y: number; displayWidth: number; foodType: FoodTypeId; textureKey: string; visualTint: number; sinkSpeed: number; calories: number; densityLevel: number }>;
  helperCreatures: Array<{ typeId: string; typeName: string; x: number; y: number; speed: number; sellPrice: Price }>;
  maxCoinDrops: number;
  coinsWaiting: Array<{
    x: number;
    y: number;
    value: number;
    coinType: CoinType;
    textureKey: string;
    tint: number;
    textColor: string;
    sinkSpeed: number;
    displayWidth: number;
    labelFontSize: number;
    bottomY: number;
    atBottom: boolean;
  }>;
};

export type AquariumTestApi = {
  getSnapshot: () => AquariumTestSnapshot;
  setFishVitals: (index: number, hunger: number, health: number) => void;
  setFishFatalCareSeconds: (index: number, seconds: number) => void;
  setFishContinuousHungerSeconds: (index: number, seconds: number) => void;
  setFishPosition: (index: number, x: number, y: number) => void;
  addFishForTest: (fishTypeId: string, x: number, y: number) => void;
  setFishGender: (index: number, gender: FishGender) => void;
  removeFishAt: (index: number) => void;
  forceCoinReady: (index: number) => void;
  forceProductionDrop: (index: number) => void;
  forceFishAge: (index: number, ageSeconds: number) => void;
  awardPrizeFishForTest: (fishTypeId: string) => void;
  useTimeCurrentForTest: () => void;
  saveNow: () => void;
  clearSave: () => void;
  backdateSave: (seconds: number) => void;
  closeModal: () => void;
  setScreen: (screen: any) => void;
  setStoreTab: (tab: StoreTab) => void;
  setStoreCoinFilter: (coinType: CoinType) => void;
  setFishCatalogLevel: (level: number) => void;
  buyFish: (fishTypeId: string) => void;
  placeFishFromInventory: (fishTypeId: string, x: number, y: number) => void;
  buyFood: (foodTypeId?: FoodTypeId) => void;
  setFoodBuyQuantity: (foodTypeId: FoodTypeId, quantity: number) => void;
  addFoodBuyQuantity: (foodTypeId: FoodTypeId, quantity: number) => void;
  resetFoodBuyQuantity: (foodTypeId: FoodTypeId) => void;
  buyDecoration: (decorationTypeId: string) => void;
  addFoodDispenserForTest: () => void;
  removeFoodDispenserForTest: () => void;
  buyHelperCreature: (creatureTypeId: string) => void;
  addHelperCreatureForTest: (creatureTypeId: string, x: number) => void;
  setHelperCreaturePosition: (index: number, x: number) => void;
  clearHelperCreatures: () => void;
  sellHelperCreatureAt: (index: number) => void;
  breedFishAt: (index: number, force?: "same" | "rare") => void;
  setFoodTool: (foodTypeId: FoodTypeId) => void;
  openSellOldest: () => void;
  sellFishAt: (index: number) => void;
  addFood: (foodTypeId: FoodTypeId, count: number) => void;
  dropFoodForTest: (foodTypeId: FoodTypeId, x: number, y: number) => void;
  dropStockedFoodForTest: (foodTypeId: FoodTypeId, x: number, y: number) => void;
  addWallet: (coinType: CoinType, amount: number) => void;
  addCoin: (coinType: CoinType, value: number, x: number, y: number) => void;
  clearCoins: () => void;
  clearFoods: () => void;
  setCleanliness: (cleanliness: number) => void;
};

declare global {
  interface Window {
    __aquariumTest?: AquariumTestApi;
  }
}
